export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8080/api'

export const EQUIPMENT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  OUT_OF_SERVICE: 'OUT_OF_SERVICE',
  RETIRED: 'RETIRED',
}

export const BOOKING_STATUS = {
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  CONFIRMED: 'CONFIRMED',
  IN_USE: 'IN_USE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
}

export const MAINTENANCE_STATUS = {
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  OVERDUE: 'OVERDUE',
}

export const NOTIFICATION_TYPES = {
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  BOOKING_REMINDER: 'BOOKING_REMINDER',
  MAINTENANCE_DUE: 'MAINTENANCE_DUE',
  CALIBRATION_EXPIRY: 'CALIBRATION_EXPIRY',
  IDLE_EQUIPMENT: 'IDLE_EQUIPMENT',
  SHARING_REQUEST: 'SHARING_REQUEST',
  EQUIPMENT_AVAILABLE: 'EQUIPMENT_AVAILABLE',
}
