package com.LabResourceUtilizationPlatform.Controller;

import com.LabResourceUtilizationPlatform.Dtos.Response.*;
import com.LabResourceUtilizationPlatform.Service.AnalyticsService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@CrossOrigin
@RequestMapping("/api/analytics")
@RequiredArgsConstructor
public class AnalyticsController {

    private final AnalyticsService analyticsService;

    /**
     * SYSTEM ADMIN
     */
    @GetMapping("/system")
    public ResponseEntity<AnalyticsDashboardResponse> getSystemAnalytics() {
        return ResponseEntity.ok(
                analyticsService.getSystemAnalytics()
        );
    }

    /**
     * INSTITUTION ADMIN
     */
    @GetMapping("/institution")
    public ResponseEntity<AnalyticsDashboardResponse> getInstitutionAnalytics() {
        return ResponseEntity.ok(
                analyticsService.getInstitutionAnalytics()
        );
    }

    /**
     * LAB MANAGER
     */
    @GetMapping("/lab")
    public ResponseEntity<AnalyticsDashboardResponse> getLabAnalytics() {
        return ResponseEntity.ok(
                analyticsService.getLabAnalytics()
        );
    }

    /**
     * Revenue generated by each equipment
     */
    @GetMapping("/revenue/equipment")
    public ResponseEntity<List<RevenueResponse>> getRevenueByEquipment() {
        return ResponseEntity.ok(
                analyticsService.getRevenueByEquipment()
        );
    }

    /**
     * Revenue generated by each lab
     */
    @GetMapping("/revenue/lab")
    public ResponseEntity<List<RevenueResponse>> getRevenueByLab() {
        return ResponseEntity.ok(
                analyticsService.getRevenueByLab()
        );
    }

    /**
     * Equipment utilization
     */
    @GetMapping("/equipment/usage")
    public ResponseEntity<List<EquipmentUsageResponse>> getEquipmentUsage() {
        return ResponseEntity.ok(
                analyticsService.getEquipmentUsage()
        );
    }

    /**
     * Top used equipment
     */
    @GetMapping("/equipment/top")
    public ResponseEntity<List<TopEquipmentResponse>> getTopUsedEquipment() {
        return ResponseEntity.ok(
                analyticsService.getTopUsedEquipment()
        );
    }

    /**
     * Least used equipment
     */
    @GetMapping("/equipment/least")
    public ResponseEntity<List<TopEquipmentResponse>> getLeastUsedEquipment() {
        return ResponseEntity.ok(
                analyticsService.getLeastUsedEquipment()
        );
    }

    /**
     * Monthly booking statistics
     */
    @GetMapping("/bookings/monthly")
    public ResponseEntity<List<MonthlyBookingResponse>> getMonthlyBookings() {
        return ResponseEntity.ok(
                analyticsService.getMonthlyBookings()
        );
    }

    /**
     * Booking trend
     */
    @GetMapping("/bookings/trend")
    public ResponseEntity<List<BookingTrendResponse>> getBookingTrend() {
        return ResponseEntity.ok(
                analyticsService.getBookingTrend()
        );
    }

    /**
     * Waiting queue analytics
     */
    @GetMapping("/waiting-queue")
    public ResponseEntity<List<WaitingQueueAnalyticsResponse>> getWaitingQueueAnalytics() {
        return ResponseEntity.ok(
                analyticsService.getWaitingQueueAnalytics()
        );
    }
}