package com.LabResourceUtilizationPlatform.Entity.Enum;

public enum NotificationType {

    BOOKING_CONFIRMATION,
    BOOKING_REMINDER,
    EQUIPMENT_AVAILABLE,
    EQUIPMENT_SHARING,
    WAITING_QUEUE,
    MAINTENANCE,
    MAINTENANCE_DUE,
    CALIBRATION_EXPIRY,
    IDLE_EQUIPMENT,
    SHARING_REQUEST,
    SHARING_APPROVED,
    EMAIL,
    SMS,
    PUSH
}
